### PR TITLE
fix: remove popups border radius and replace popups buttons

### PR DESCRIPTION
**Pull request by CillianFrost**
https://jira.railsc.ru/browse/GOODS-2623

### CODE REVIEW

**Comment by CillianFrost** [comment]
@Nats92 => @ idbolshakov

**Review by Nats92 — APPROVED** [review]

**Comment by Nats92** [comment]
@idbolshakov

**Review by endiko — APPROVED** [review]

**Comment by CillianFrost** [comment]
@TamarinEA

**Comment by TamarinEA** [comment]
конфликт

**Pull request merged**
