### PR TITLE
feat: show save status for tree nodes moving

### PR DESCRIPTION
**Pull request by CillianFrost**
https://jira.railsc.ru/browse/GOODS-2645

### CODE REVIEW

**Comment by CillianFrost** [comment]
@Nats92 => @ idbolshakov

**Review by Nats92 — APPROVED** [review]

**Comment by Nats92** [comment]
@idbolshakov

**Review by idbolshakov — APPROVED** [review]

**Comment by CillianFrost** [comment]
@TamarinEA

**Comment by TamarinEA** [comment]
конфликты

**Comment by CillianFrost** [comment]
@TamarinEA

**Pull request merged**
